### ISSUE TITLE
launch.sh is not present?

### ISSUE THREAD

**Issue by minhducsun2002** [Rashad-707/dotfiles#2]
https://github.com/Rashad-707/dotfiles/blob/main/.bin/loadPolybar links to `$HOME/.config/polybar/launch.sh`, which seemingly does not exist under https://github.com/Rashad-707/dotfiles/tree/main/.config.

Could you please supply the file or at least describe what does it do? 

Thank you very much.

**Comment by Rashad-707** [comment]
Sorry for late response, the files are available inside the theme folder eg. `~/.config/polybar/theme-1` you have to copy all the files of the theme you want into `~/.config/polybar` including launch.sh
